version: '3.2'

services:
  api:
    build: .
    command: uvicorn api.main:app --reload --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=otakker
      - POSTGRES_DB=otakker

volumes:
  postgres_data: